version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - php
    networks:
      - default

  php:
    container_name: php
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/symfony
    working_dir: /var/www/symfony
    command: >
      sh -c "cd /var/www/symfony && composer require && php-fpm -F"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  db_data:

networks:
  default: